export const editorTheme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "editor-placeholder",
    paragraph: "mb-2 relative",
    quote: "pl-4 border-l-4 border-border italic text-muted-foreground mb-4",
    heading: {
        h1: "text-3xl font-bold text-foreground mb-4 mt-6",
        h2: "text-2xl font-semibold text-foreground mb-3 mt-5",
        h3: "text-xl font-medium text-foreground mb-2 mt-4",
        h4: "text-lg font-medium text-foreground mb-2 mt-4",
        h5: "text-base font-bold text-foreground mb-1 mt-2",
        h6: "text-sm font-bold text-foreground mb-1 mt-2",
    },
    list: {
        nested: {
            listitem: "list-none",
        },
        ol: "list-decimal list-inside mb-4 pl-4",
        ul: "list-disc list-inside mb-4 pl-4",
        listitem: "mb-1",
        listitemChecked: "list-none relative pl-8 line-through text-muted-foreground before:content-['✓'] before:text-xs before:flex before:items-center before:justify-center before:font-bold before:text-primary-foreground before:bg-primary before:absolute before:left-0 before:top-1 before:w-4 before:h-4 before:border before:border-primary before:rounded",
        listitemUnchecked: "list-none relative pl-8 before:content-[''] before:absolute before:left-0 before:top-1 before:w-4 before:h-4 before:border before:border-muted-foreground before:rounded",
    },
    table: "border-collapse border border-border w-full my-4",
    tableCell: "border border-border px-4 py-2 relative",
    tableCellHeader: "bg-muted font-bold",
    hashtag: "text-primary font-bold hover:underline cursor-pointer",
    mark: "bg-yellow-100 dark:bg-yellow-900 text-foreground px-1 rounded-sm",
    image: "editor-image",
    link: "text-primary hover:underline cursor-pointer",
    text: {
        bold: "font-bold",
        italic: "italic",
        overflowed: "editor-text-overflowed",
        hashtag: "editor-text-hashtag",
        underline: "underline",
        strikethrough: "line-through",
        underlineStrikethrough: "underline line-through",
        code: "bg-muted px-1 py-0.5 rounded text-sm font-mono text-destructive",
    },
    code: "bg-muted p-4 rounded-lg overflow-x-auto mb-4 font-mono text-sm block",
    codeHighlight: {
        atrule: "editor-tokenAttr",
        attr: "editor-tokenAttr",
        boolean: "editor-tokenProperty",
        builtin: "editor-tokenSelector",
        cdata: "editor-tokenComment",
        char: "editor-tokenSelector",
        class: "editor-tokenFunction",
        "class-name": "editor-tokenFunction",
        comment: "editor-tokenComment",
        constant: "editor-tokenProperty",
        deleted: "editor-tokenProperty",
        doctype: "editor-tokenComment",
        entity: "editor-tokenOperator",
        function: "editor-tokenFunction",
        important: "editor-tokenVariable",
        inserted: "editor-tokenSelector",
        keyword: "editor-tokenAttr",
        namespace: "editor-tokenVariable",
        number: "editor-tokenProperty",
        operator: "editor-tokenOperator",
        prolog: "editor-tokenComment",
        property: "editor-tokenProperty",
        punctuation: "editor-tokenPunctuation",
        regex: "editor-tokenVariable",
        selector: "editor-tokenSelector",
        string: "editor-tokenSelector",
        symbol: "editor-tokenProperty",
        tag: "editor-tokenProperty",
        url: "editor-tokenOperator",
        variable: "editor-tokenVariable",
    },
};
