@startwbs
skinparam backgroundColor white
skinparam shadowing false

* notefiber-FE
** dist
*** assets
*** fonts
** docs
*** api
*** crop
*** INSTRUCTION
*** lexical
** node_modules
** public
*** fonts
** src
*** api
**** client
***** interceptors
**** config
**** services
***** auth
***** location
***** payment
***** user
**** types
*** assets
**** images
***** landing
****** avatar
****** backgrounds
****** icons
****** illustrations
****** logo
****** texture
*** components
**** auth
**** common
**** modals
**** organisms
***** Editor
****** plugins
******* toolbar
**** shadui
**** ui
*** config
*** constants
*** contexts
*** dto
*** features
*** hooks
**** auth
**** location
**** payment
**** user
*** lib
*** pages
**** auth
***** components
**** checkout
***** components
**** landingpage
***** components
****** atoms
****** molecules
****** organisms
**** pricing
**** user
*** routes
*** styles
*** types
*** utils
**** debug
**** error
**** storage
**** validators
** components.json
** package-lock.json
** package.json
** tsconfig.app.json
** tsconfig.json
** tsconfig.node.json
** vite.config.ts

@endwbs