export const API_CONSTANTS = {
  TIMEOUT: 0, // 30s
  RETRY_COUNT: 3,
  RETRY_DELAY: 1000,
  HEADER_AUTH: "Authorization",
  TOKEN_PREFIX: "Bearer",
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;
