/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as authValidateCodeRouteImport } from './routes/(auth)/validate-code'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedRefundsRefundIdRouteImport } from './routes/_authenticated/refunds.$refundId'
import { Route as AuthenticatedCancellationsCancellationIdRouteImport } from './routes/_authenticated/cancellations.$cancellationId'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app.subscription'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSubscriptionIndexRouteImport } from './routes/_authenticated/app.subscription.index'
import { Route as AuthenticatedAppUsersUserIdRouteImport } from './routes/_authenticated/app.users.$userId'
import { Route as AuthenticatedAppSubscriptionHistoryRouteImport } from './routes/_authenticated/app.subscription.history'
import { Route as AuthenticatedAppRefundsRefundIdRouteImport } from './routes/_authenticated/app.refunds.$refundId'
import { Route as AuthenticatedAppNoteNoteIdRouteImport } from './routes/_authenticated/app.note.$noteId'
import { Route as AuthenticatedAppCancellationsCancellationIdRouteImport } from './routes/_authenticated/app.cancellations.$cancellationId'
import { Route as AuthenticatedAppSubscriptionRefundsHistoryRouteImport } from './routes/_authenticated/app.subscription.refunds.history'
import { Route as AuthenticatedAppSubscriptionRefundsRefundIdRouteImport } from './routes/_authenticated/app.subscription.refunds.$refundId'
import { Route as AuthenticatedAppSubscriptionCancellationCancellationIdRouteImport } from './routes/_authenticated/app.subscription.cancellation.$cancellationId'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authValidateCodeRoute = authValidateCodeRouteImport.update({
  id: '/(auth)/validate-code',
  path: '/validate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRefundsRefundIdRoute =
  AuthenticatedRefundsRefundIdRouteImport.update({
    id: '/refunds/$refundId',
    path: '/refunds/$refundId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCancellationsCancellationIdRoute =
  AuthenticatedCancellationsCancellationIdRouteImport.update({
    id: '/cancellations/$cancellationId',
    path: '/cancellations/$cancellationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSubscriptionIndexRoute =
  AuthenticatedAppSubscriptionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSubscriptionRoute,
  } as any)
const AuthenticatedAppUsersUserIdRoute =
  AuthenticatedAppUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSubscriptionHistoryRoute =
  AuthenticatedAppSubscriptionHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAppSubscriptionRoute,
  } as any)
const AuthenticatedAppRefundsRefundIdRoute =
  AuthenticatedAppRefundsRefundIdRouteImport.update({
    id: '/refunds/$refundId',
    path: '/refunds/$refundId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNoteNoteIdRoute =
  AuthenticatedAppNoteNoteIdRouteImport.update({
    id: '/note/$noteId',
    path: '/note/$noteId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCancellationsCancellationIdRoute =
  AuthenticatedAppCancellationsCancellationIdRouteImport.update({
    id: '/cancellations/$cancellationId',
    path: '/cancellations/$cancellationId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSubscriptionRefundsHistoryRoute =
  AuthenticatedAppSubscriptionRefundsHistoryRouteImport.update({
    id: '/refunds/history',
    path: '/refunds/history',
    getParentRoute: () => AuthenticatedAppSubscriptionRoute,
  } as any)
const AuthenticatedAppSubscriptionRefundsRefundIdRoute =
  AuthenticatedAppSubscriptionRefundsRefundIdRouteImport.update({
    id: '/refunds/$refundId',
    path: '/refunds/$refundId',
    getParentRoute: () => AuthenticatedAppSubscriptionRoute,
  } as any)
const AuthenticatedAppSubscriptionCancellationCancellationIdRoute =
  AuthenticatedAppSubscriptionCancellationCancellationIdRouteImport.update({
    id: '/cancellation/$cancellationId',
    path: '/cancellation/$cancellationId',
    getParentRoute: () => AuthenticatedAppSubscriptionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/validate-code': typeof authValidateCodeRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/admin/$': typeof AdminSplatRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRouteWithChildren
  '/cancellations/$cancellationId': typeof AuthenticatedCancellationsCancellationIdRoute
  '/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/cancellations/$cancellationId': typeof AuthenticatedAppCancellationsCancellationIdRoute
  '/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
  '/app/refunds/$refundId': typeof AuthenticatedAppRefundsRefundIdRoute
  '/app/subscription/history': typeof AuthenticatedAppSubscriptionHistoryRoute
  '/app/users/$userId': typeof AuthenticatedAppUsersUserIdRoute
  '/app/subscription/': typeof AuthenticatedAppSubscriptionIndexRoute
  '/app/subscription/cancellation/$cancellationId': typeof AuthenticatedAppSubscriptionCancellationCancellationIdRoute
  '/app/subscription/refunds/$refundId': typeof AuthenticatedAppSubscriptionRefundsRefundIdRoute
  '/app/subscription/refunds/history': typeof AuthenticatedAppSubscriptionRefundsHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/validate-code': typeof authValidateCodeRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/admin/$': typeof AdminSplatRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/cancellations/$cancellationId': typeof AuthenticatedCancellationsCancellationIdRoute
  '/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/cancellations/$cancellationId': typeof AuthenticatedAppCancellationsCancellationIdRoute
  '/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
  '/app/refunds/$refundId': typeof AuthenticatedAppRefundsRefundIdRoute
  '/app/subscription/history': typeof AuthenticatedAppSubscriptionHistoryRoute
  '/app/users/$userId': typeof AuthenticatedAppUsersUserIdRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionIndexRoute
  '/app/subscription/cancellation/$cancellationId': typeof AuthenticatedAppSubscriptionCancellationCancellationIdRoute
  '/app/subscription/refunds/$refundId': typeof AuthenticatedAppSubscriptionRefundsRefundIdRoute
  '/app/subscription/refunds/history': typeof AuthenticatedAppSubscriptionRefundsHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/landing': typeof LandingRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/validate-code': typeof authValidateCodeRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/admin/$': typeof AdminSplatRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRouteWithChildren
  '/_authenticated/cancellations/$cancellationId': typeof AuthenticatedCancellationsCancellationIdRoute
  '/_authenticated/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/cancellations/$cancellationId': typeof AuthenticatedAppCancellationsCancellationIdRoute
  '/_authenticated/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
  '/_authenticated/app/refunds/$refundId': typeof AuthenticatedAppRefundsRefundIdRoute
  '/_authenticated/app/subscription/history': typeof AuthenticatedAppSubscriptionHistoryRoute
  '/_authenticated/app/users/$userId': typeof AuthenticatedAppUsersUserIdRoute
  '/_authenticated/app/subscription/': typeof AuthenticatedAppSubscriptionIndexRoute
  '/_authenticated/app/subscription/cancellation/$cancellationId': typeof AuthenticatedAppSubscriptionCancellationCancellationIdRoute
  '/_authenticated/app/subscription/refunds/$refundId': typeof AuthenticatedAppSubscriptionRefundsRefundIdRoute
  '/_authenticated/app/subscription/refunds/history': typeof AuthenticatedAppSubscriptionRefundsHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/validate-code'
    | '/app'
    | '/checkout'
    | '/pricing'
    | '/admin/$'
    | '/app/settings'
    | '/app/subscription'
    | '/cancellations/$cancellationId'
    | '/refunds/$refundId'
    | '/users/$userId'
    | '/app/'
    | '/app/cancellations/$cancellationId'
    | '/app/note/$noteId'
    | '/app/refunds/$refundId'
    | '/app/subscription/history'
    | '/app/users/$userId'
    | '/app/subscription/'
    | '/app/subscription/cancellation/$cancellationId'
    | '/app/subscription/refunds/$refundId'
    | '/app/subscription/refunds/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/validate-code'
    | '/checkout'
    | '/pricing'
    | '/admin/$'
    | '/app/settings'
    | '/cancellations/$cancellationId'
    | '/refunds/$refundId'
    | '/users/$userId'
    | '/app'
    | '/app/cancellations/$cancellationId'
    | '/app/note/$noteId'
    | '/app/refunds/$refundId'
    | '/app/subscription/history'
    | '/app/users/$userId'
    | '/app/subscription'
    | '/app/subscription/cancellation/$cancellationId'
    | '/app/subscription/refunds/$refundId'
    | '/app/subscription/refunds/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/landing'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/validate-code'
    | '/_authenticated/app'
    | '/_authenticated/checkout'
    | '/_authenticated/pricing'
    | '/admin/$'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/subscription'
    | '/_authenticated/cancellations/$cancellationId'
    | '/_authenticated/refunds/$refundId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/app/'
    | '/_authenticated/app/cancellations/$cancellationId'
    | '/_authenticated/app/note/$noteId'
    | '/_authenticated/app/refunds/$refundId'
    | '/_authenticated/app/subscription/history'
    | '/_authenticated/app/users/$userId'
    | '/_authenticated/app/subscription/'
    | '/_authenticated/app/subscription/cancellation/$cancellationId'
    | '/_authenticated/app/subscription/refunds/$refundId'
    | '/_authenticated/app/subscription/refunds/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authValidateCodeRoute: typeof authValidateCodeRoute
  AdminSplatRoute: typeof AdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/validate-code': {
      id: '/(auth)/validate-code'
      path: '/validate-code'
      fullPath: '/validate-code'
      preLoaderRoute: typeof authValidateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refunds/$refundId': {
      id: '/_authenticated/refunds/$refundId'
      path: '/refunds/$refundId'
      fullPath: '/refunds/$refundId'
      preLoaderRoute: typeof AuthenticatedRefundsRefundIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cancellations/$cancellationId': {
      id: '/_authenticated/cancellations/$cancellationId'
      path: '/cancellations/$cancellationId'
      fullPath: '/cancellations/$cancellationId'
      preLoaderRoute: typeof AuthenticatedCancellationsCancellationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription/': {
      id: '/_authenticated/app/subscription/'
      path: '/'
      fullPath: '/app/subscription/'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedAppSubscriptionRoute
    }
    '/_authenticated/app/users/$userId': {
      id: '/_authenticated/app/users/$userId'
      path: '/users/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AuthenticatedAppUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription/history': {
      id: '/_authenticated/app/subscription/history'
      path: '/history'
      fullPath: '/app/subscription/history'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionHistoryRouteImport
      parentRoute: typeof AuthenticatedAppSubscriptionRoute
    }
    '/_authenticated/app/refunds/$refundId': {
      id: '/_authenticated/app/refunds/$refundId'
      path: '/refunds/$refundId'
      fullPath: '/app/refunds/$refundId'
      preLoaderRoute: typeof AuthenticatedAppRefundsRefundIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/note/$noteId': {
      id: '/_authenticated/app/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/app/note/$noteId'
      preLoaderRoute: typeof AuthenticatedAppNoteNoteIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cancellations/$cancellationId': {
      id: '/_authenticated/app/cancellations/$cancellationId'
      path: '/cancellations/$cancellationId'
      fullPath: '/app/cancellations/$cancellationId'
      preLoaderRoute: typeof AuthenticatedAppCancellationsCancellationIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription/refunds/history': {
      id: '/_authenticated/app/subscription/refunds/history'
      path: '/refunds/history'
      fullPath: '/app/subscription/refunds/history'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRefundsHistoryRouteImport
      parentRoute: typeof AuthenticatedAppSubscriptionRoute
    }
    '/_authenticated/app/subscription/refunds/$refundId': {
      id: '/_authenticated/app/subscription/refunds/$refundId'
      path: '/refunds/$refundId'
      fullPath: '/app/subscription/refunds/$refundId'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRefundsRefundIdRouteImport
      parentRoute: typeof AuthenticatedAppSubscriptionRoute
    }
    '/_authenticated/app/subscription/cancellation/$cancellationId': {
      id: '/_authenticated/app/subscription/cancellation/$cancellationId'
      path: '/cancellation/$cancellationId'
      fullPath: '/app/subscription/cancellation/$cancellationId'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionCancellationCancellationIdRouteImport
      parentRoute: typeof AuthenticatedAppSubscriptionRoute
    }
  }
}

interface AuthenticatedAppSubscriptionRouteChildren {
  AuthenticatedAppSubscriptionHistoryRoute: typeof AuthenticatedAppSubscriptionHistoryRoute
  AuthenticatedAppSubscriptionIndexRoute: typeof AuthenticatedAppSubscriptionIndexRoute
  AuthenticatedAppSubscriptionCancellationCancellationIdRoute: typeof AuthenticatedAppSubscriptionCancellationCancellationIdRoute
  AuthenticatedAppSubscriptionRefundsRefundIdRoute: typeof AuthenticatedAppSubscriptionRefundsRefundIdRoute
  AuthenticatedAppSubscriptionRefundsHistoryRoute: typeof AuthenticatedAppSubscriptionRefundsHistoryRoute
}

const AuthenticatedAppSubscriptionRouteChildren: AuthenticatedAppSubscriptionRouteChildren =
  {
    AuthenticatedAppSubscriptionHistoryRoute:
      AuthenticatedAppSubscriptionHistoryRoute,
    AuthenticatedAppSubscriptionIndexRoute:
      AuthenticatedAppSubscriptionIndexRoute,
    AuthenticatedAppSubscriptionCancellationCancellationIdRoute:
      AuthenticatedAppSubscriptionCancellationCancellationIdRoute,
    AuthenticatedAppSubscriptionRefundsRefundIdRoute:
      AuthenticatedAppSubscriptionRefundsRefundIdRoute,
    AuthenticatedAppSubscriptionRefundsHistoryRoute:
      AuthenticatedAppSubscriptionRefundsHistoryRoute,
  }

const AuthenticatedAppSubscriptionRouteWithChildren =
  AuthenticatedAppSubscriptionRoute._addFileChildren(
    AuthenticatedAppSubscriptionRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCancellationsCancellationIdRoute: typeof AuthenticatedAppCancellationsCancellationIdRoute
  AuthenticatedAppNoteNoteIdRoute: typeof AuthenticatedAppNoteNoteIdRoute
  AuthenticatedAppRefundsRefundIdRoute: typeof AuthenticatedAppRefundsRefundIdRoute
  AuthenticatedAppUsersUserIdRoute: typeof AuthenticatedAppUsersUserIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSubscriptionRoute:
    AuthenticatedAppSubscriptionRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCancellationsCancellationIdRoute:
    AuthenticatedAppCancellationsCancellationIdRoute,
  AuthenticatedAppNoteNoteIdRoute: AuthenticatedAppNoteNoteIdRoute,
  AuthenticatedAppRefundsRefundIdRoute: AuthenticatedAppRefundsRefundIdRoute,
  AuthenticatedAppUsersUserIdRoute: AuthenticatedAppUsersUserIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedCancellationsCancellationIdRoute: typeof AuthenticatedCancellationsCancellationIdRoute
  AuthenticatedRefundsRefundIdRoute: typeof AuthenticatedRefundsRefundIdRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedCancellationsCancellationIdRoute:
    AuthenticatedCancellationsCancellationIdRoute,
  AuthenticatedRefundsRefundIdRoute: AuthenticatedRefundsRefundIdRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authValidateCodeRoute: authValidateCodeRoute,
  AdminSplatRoute: AdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
